-- Migration 006: SEED intermediate SKUs (generated, chef v2 + base_unit)
-- Source: seed_data/intermediate-sku-master-v2.xlsx (46 rows). sku_type='intermediate'.
-- base_unit for recipes; sort_order = chef's by-volume order. Regenerate: gen_seed_sql.py.

insert into skus (code, name, sku_type, category, category_canonical, uom, base_unit, typical_qty_per_day, sort_order, to_spokes, shelf_life_days, notes) values
  ('INT-SPG-001', 'Chocolate Sponge 5in (500g)', 'intermediate'::sku_type, 'Sponge', 'Sponge', 'Pieces', 'piece'::base_unit, 800, 1, false, null, 'Base for most chocolate cakes'),
  ('INT-SPG-002', 'Vanilla Sponge 5in (500g)', 'intermediate'::sku_type, 'Sponge', 'Sponge', 'Pieces', 'piece'::base_unit, 600, 2, false, null, null),
  ('INT-SPG-003', 'Chocolate Sponge 6in (500g)', 'intermediate'::sku_type, 'Sponge', 'Sponge', 'Pieces', 'piece'::base_unit, 120, 3, true, null, 'Mostly used in designer cakes'),
  ('INT-SPG-004', 'Chocolate Sponge 7in (1kg)', 'intermediate'::sku_type, 'Sponge', 'Sponge', 'Pieces', 'piece'::base_unit, 120, 4, true, null, null),
  ('INT-SPG-005', 'Vanilla Sponge 6in (500g)', 'intermediate'::sku_type, 'Sponge', 'Sponge', 'Pieces', 'piece'::base_unit, 120, 5, true, null, 'Designer cakes / Tiramisu'),
  ('INT-SPG-006', 'Vanilla Sponge 7in (1kg)', 'intermediate'::sku_type, 'Sponge', 'Sponge', 'Pieces', 'piece'::base_unit, 50, 6, true, null, null),
  ('INT-SPG-007', 'Chocolate Pastry Sponge 8in', 'intermediate'::sku_type, 'Sponge', 'Sponge', 'Pieces', 'piece'::base_unit, 40, 7, true, null, null),
  ('INT-SPG-008', 'Vanilla Pastry Sponge 8in', 'intermediate'::sku_type, 'Sponge', 'Sponge', 'Pieces', 'piece'::base_unit, 30, 8, false, null, null),
  ('INT-SPG-009', 'Chocolate Sponge Scratch Tray', 'intermediate'::sku_type, 'Sponge', 'Sponge', 'Trays', 'piece'::base_unit, 28, 9, false, null, 'Made daily'),
  ('INT-SPG-010', 'Chocolate Sponge Tray', 'intermediate'::sku_type, 'Sponge', 'Sponge', 'Trays', 'piece'::base_unit, 18, 10, true, null, 'Used in both kitchens | FLAG: tray/mould size?'),
  ('INT-SPG-011', 'Vanilla Sponge Tray', 'intermediate'::sku_type, 'Sponge', 'Sponge', 'Trays', 'piece'::base_unit, 12, 11, true, null, 'FLAG: tray/mould size?'),
  ('INT-SPG-012', 'Red Velvet Sponge Tray', 'intermediate'::sku_type, 'Sponge', 'Sponge', 'Trays', 'piece'::base_unit, 10, 12, true, null, 'FLAG: tray/mould size?'),
  ('INT-SPG-013', 'Red Velvet Pastry Sponge 8in', 'intermediate'::sku_type, 'Sponge', 'Sponge', 'Pieces', 'piece'::base_unit, 8, 13, false, null, null),
  ('INT-SPG-014', 'Sugar-Free Chocolate Sponge Scratch Tray', 'intermediate'::sku_type, 'Sponge', 'Sponge', 'Trays', 'piece'::base_unit, null, 14, false, 3, 'One batch lasts three days | shelf life inferred from note'),
  ('INT-GAN-001', 'COD-16 Truffle Ganache (Classic)', 'intermediate'::sku_type, 'Ganache', 'Ganache', 'Kg', 'gram'::base_unit, 250, 15, false, null, null),
  ('INT-GAN-002', 'COD-16 Truffle Ganache (Designer)', 'intermediate'::sku_type, 'Ganache', 'Ganache', 'Kg', 'gram'::base_unit, 100, 16, true, null, null),
  ('INT-GAN-003', 'VHP-46.5% Chocolate Ganache', 'intermediate'::sku_type, 'Ganache', 'Ganache', 'Kg', 'gram'::base_unit, 40, 17, false, null, null),
  ('INT-GAN-004', 'Dairy Milk Chocolate Ganache', 'intermediate'::sku_type, 'Ganache', 'Ganache', 'Kg', 'gram'::base_unit, 30, 18, true, null, 'Distinct from Whipped'),
  ('INT-GAN-005', 'VHP-46.5% Whipped Chocolate Ganache', 'intermediate'::sku_type, 'Ganache', 'Ganache', 'Kg', 'gram'::base_unit, 30, 19, false, null, 'corrected: chocolate, not cream'),
  ('INT-GAN-006', 'Whipped Pistachio Ganache', 'intermediate'::sku_type, 'Ganache', 'Ganache', 'Kg', 'gram'::base_unit, 15, 20, false, null, null),
  ('INT-GAN-007', 'Cremeux Ganache', 'intermediate'::sku_type, 'Ganache', 'Ganache', 'Kg', 'gram'::base_unit, 10, 21, false, null, null),
  ('INT-GAN-008', 'Almond Flakes (Roasted)', 'intermediate'::sku_type, 'Ganache', 'Ganache', 'Kg', 'gram'::base_unit, 10, 22, false, null, 'roasted in-house'),
  ('INT-GAN-009', 'Milk Chocolate Almond Ganache', 'intermediate'::sku_type, 'Ganache', 'Ganache', 'Kg', 'gram'::base_unit, 6, 23, false, null, 'Made on demand'),
  ('INT-GAN-010', 'Whipped Milk Chocolate Ganache', 'intermediate'::sku_type, 'Ganache', 'Ganache', 'Kg', 'gram'::base_unit, 4, 24, false, null, 'Distinct from Dairy Milk'),
  ('INT-GAN-011', 'Caramel Whipped Ganache', 'intermediate'::sku_type, 'Ganache', 'Ganache', 'Kg', 'gram'::base_unit, 4, 25, false, null, null),
  ('INT-GAN-012', 'Pouring Ganache', 'intermediate'::sku_type, 'Ganache', 'Ganache', 'Kg', 'gram'::base_unit, 3, 26, false, null, null),
  ('INT-GAN-013', 'Vanilla Custard Cream', 'intermediate'::sku_type, 'Ganache', 'Ganache', 'Kg', 'gram'::base_unit, 3, 27, false, null, null),
  ('INT-GAN-014', 'Malai Cream', 'intermediate'::sku_type, 'Ganache', 'Ganache', 'Kg', 'gram'::base_unit, 2.5, 28, false, null, 'name per chef: Malai Cream'),
  ('INT-GAN-015', 'Sugar-Free Chocolate Ganache', 'intermediate'::sku_type, 'Ganache', 'Ganache', 'Kg', 'gram'::base_unit, 2, 29, false, null, null),
  ('INT-GAN-016', 'White Chocolate Ganache', 'intermediate'::sku_type, 'Ganache', 'Ganache', 'Kg', 'gram'::base_unit, 2, 30, false, null, null),
  ('INT-SUB-001', 'Sugar Syrup', 'intermediate'::sku_type, 'Sub-component', 'Sub-component', 'Kg', 'gram'::base_unit, 70, 31, false, null, null),
  ('INT-SUB-002', 'Butter Cream', 'intermediate'::sku_type, 'Sub-component', 'Sub-component', 'Kg', 'gram'::base_unit, 60, 32, true, null, null),
  ('INT-SUB-003', 'Cream Cheese Frosting', 'intermediate'::sku_type, 'Sub-component', 'Sub-component', 'Kg', 'gram'::base_unit, 30, 33, true, null, null),
  ('INT-SUB-004', 'Salted Caramel', 'intermediate'::sku_type, 'Sub-component', 'Sub-component', 'Kg', 'gram'::base_unit, 18, 34, true, 7, 'Made rarely, ~1 week shelf life | shelf life inferred from note'),
  ('INT-SUB-005', 'Salted Caramel (Overcooked)', 'intermediate'::sku_type, 'Sub-component', 'Sub-component', 'Kg', 'gram'::base_unit, 10, 35, false, null, 'NEW item, not in first list'),
  ('INT-SUB-006', 'Cocoa Streusel', 'intermediate'::sku_type, 'Sub-component', 'Sub-component', 'Kg', 'gram'::base_unit, 10, 36, false, null, null),
  ('INT-SUB-007', 'Roasted Pistachio', 'intermediate'::sku_type, 'Sub-component', 'Sub-component', 'Kg', 'gram'::base_unit, 10, 37, false, null, null),
  ('INT-SUB-008', 'Mango Compote', 'intermediate'::sku_type, 'Sub-component', 'Sub-component', 'Kg', 'gram'::base_unit, 8, 38, false, null, null),
  ('INT-SUB-009', 'Sticking Butter Cream', 'intermediate'::sku_type, 'Sub-component', 'Sub-component', 'Kg', 'gram'::base_unit, 5, 39, false, null, null),
  ('INT-SUB-010', 'Roasted Vermicelli', 'intermediate'::sku_type, 'Sub-component', 'Sub-component', 'Kg', 'gram'::base_unit, 5, 40, false, null, null),
  ('INT-SUB-011', 'Butterscotch Chunk Glaze', 'intermediate'::sku_type, 'Sub-component', 'Sub-component', 'Kg', 'gram'::base_unit, 4, 41, false, null, null),
  ('INT-SUB-012', 'Cocoa Rocher Glaze (Bomboloni)', 'intermediate'::sku_type, 'Sub-component', 'Sub-component', 'Kg', 'gram'::base_unit, 4, 42, false, null, null),
  ('INT-SUB-013', 'Almond Rocher Glaze', 'intermediate'::sku_type, 'Sub-component', 'Sub-component', 'Kg', 'gram'::base_unit, 3, 43, false, null, null),
  ('INT-SUB-014', 'Butterscotch Whip', 'intermediate'::sku_type, 'Sub-component', 'Sub-component', 'Kg', 'gram'::base_unit, 3, 44, false, null, null),
  ('INT-SUB-015', 'Caramelized Hazelnuts', 'intermediate'::sku_type, 'Sub-component', 'Sub-component', 'Kg', 'gram'::base_unit, 1, 45, true, null, null),
  ('INT-SUB-016', 'Cooked Condensed Milk', 'intermediate'::sku_type, 'Sub-component', 'Sub-component', 'Kg', 'gram'::base_unit, null, 46, false, null, 'Purchased milkmaid, cooked 5 hours | purchased input, only processed')
on conflict (code) do nothing;

